sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456789
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: your-key-id
    access-key-secret: your-key-secret
    bucket-name: aliyun-demo0